title: "自动语音识别"
type: community
group: 音频/语音处理
image: /static/templates/automatic-speech-recognition.png
details: |
  <h1>转录音频内容</h1>
  <dl>
    <dt>行业应用</dt>
    <dd>播客转录、会议记录、呼叫中心、客户服务、无障碍、隐藏字幕、字幕、语音助手、听写、医疗听写、法律转录</dd>
    <dt>相关模型</dt>
    <dd>Whisper、Wav2Vec、DeepSpeech、transformer、CTC</dd>
    <dt>领域术语</dt>
    <dd>ASR、STT、语音转文字、转录、语音识别、语音处理、音频转录</dd>
  </dl>
config: |
  <View>
    <Audio name="audio" value="$audio" zoom="true" hotkey="ctrl+enter" />
    <Header value="Transcribe the audio" />
    <TextArea name="transcription" toName="audio"
              rows="4" editable="true" maxSubmissions="1" />
  </View>

