# Generated by Django 5.1.9 on 2025-06-26 20:30

from django.db import migrations
from django.conf import settings
from core.models import AsyncMigrationStatus
from core.redis import start_job_async_or_sync
import logging
logger = logging.getLogger(__name__)

IS_SQLITE = settings.DJANGO_DB == settings.DJANGO_DB_SQLITE

migration_name = '0055_task_proj_octlen_idx_async'

def get_sql_create_index(db_vendor):
    if db_vendor == 'postgresql':
        return (
            'CREATE INDEX CONCURRENTLY IF NOT EXISTS task_proj_octlen_idx '
            'ON task (project_id, octet_length(data::text) DESC) '
            'INCLUDE (id);'
        )
    elif db_vendor == 'mysql':
        # MySQL doesn't support CONCURRENTLY or INCLUDE clause
        # For MySQL, create a simpler index without the JSON length
        return (
            'CREATE INDEX task_proj_octlen_idx '
            'ON `task` (`project_id`, `id`);'
        )
    else:
        return None

def get_sql_drop_index(db_vendor):
    if db_vendor == 'postgresql':
        return 'DROP INDEX CONCURRENTLY IF EXISTS task_proj_octlen_idx;'
    elif db_vendor == 'mysql':
        return 'DROP INDEX `task_proj_octlen_idx` ON `task`;'
    else:
        return None

def forward_migration(migration_name, db_alias):
    migration, created = AsyncMigrationStatus.objects.using(db_alias).get_or_create(
        name=migration_name,
        defaults={'status': AsyncMigrationStatus.STATUS_STARTED},
    )
    if not created:
        return
    
    logger.info(f'Start async migration {migration_name}')
    from django.db import connections
    conn = connections[db_alias]
    db_vendor = conn.vendor
    
    sql = get_sql_create_index(db_vendor)
    if sql is None:
        logger.info(f'Skipping index creation for {db_vendor} database')
        migration.status = AsyncMigrationStatus.STATUS_FINISHED
        migration.save(using=db_alias)
        return
    
    if db_vendor == 'mysql':
        # Try to drop existing index first (if any)
        try:
            conn.cursor().execute(get_sql_drop_index(db_vendor))
        except Exception:
            pass
    
    cursor = conn.cursor()
    cursor.execute(sql)
    migration.status = AsyncMigrationStatus.STATUS_FINISHED
    migration.save(using=db_alias)
    logger.info(f'Async migration {migration_name} complete')

def backward_migration(migration_name, db_alias):
    migration = AsyncMigrationStatus.objects.using(db_alias).create(
        name=migration_name,
        status=AsyncMigrationStatus.STATUS_STARTED,
    )
    logger.info(f'Start revert of async migration {migration_name}')
    from django.db import connections
    conn = connections[db_alias]
    db_vendor = conn.vendor
    
    sql = get_sql_drop_index(db_vendor)
    if sql is None:
        logger.info(f'Skipping index drop for {db_vendor} database')
        migration.status = AsyncMigrationStatus.STATUS_FINISHED
        migration.save(using=db_alias)
        return
    
    if db_vendor == 'mysql':
        # MySQL may not have the index, ignore errors
        try:
            conn.cursor().execute(sql)
        except Exception:
            pass
    else:
        cursor = conn.cursor()
        cursor.execute(sql)
    
    migration.status = AsyncMigrationStatus.STATUS_FINISHED
    migration.save(using=db_alias)
    logger.info(f'Async migration {migration_name} revert complete')

def forwards(apps, schema_editor):
    if IS_SQLITE:
        logger.info('SQLite execution')
        logger.info('Skipping async index creation for non-PostgreSQL databases')
        return
    
    db_vendor = schema_editor.connection.vendor
    if db_vendor not in ['postgresql', 'mysql']:
        logger.info(f'Skipping async index creation for {db_vendor} database')
        return

    db_alias = schema_editor.connection.alias
    start_job_async_or_sync(forward_migration, migration_name=migration_name, db_alias=db_alias)

def backwards(apps, schema_editor):
    db_vendor = schema_editor.connection.vendor
    if db_vendor not in ['postgresql', 'mysql']:
        logger.info(f'Skipping async index drop for {db_vendor} database')
        return
    
    db_alias = schema_editor.connection.alias
    start_job_async_or_sync(backward_migration, migration_name=migration_name, db_alias=db_alias)

class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("tasks", "0054_add_brin_index_updated_at"),
    ]
    operations = [
        migrations.RunPython(forwards, backwards),
    ]
