title: "视觉基因组"
type: community
group: 计算机视觉
image: /static/templates/visual-genome.png
details: |
  <h1>对图像中的物体、属性和关系进行标注</h1>
  <dl>
    <dt>行业应用</dt>
    <dd>场景理解、关系检测、视觉推理、知识图谱构建</dd>
    <dt>相关模型</dt>
    <dd>Visual Genome、Scene Graph、VG</dd>
    <dt>领域术语</dt>
    <dd>场景图、关系标注、属性标注、视觉知识</dd>
  </dl>
config: |
  <View>
    <View style="display: flex; flex-wrap: wrap;">
      <View className="label-column">
        <Header value="Regions"/>
        <RectangleLabels name="regions" toName="image" value="$regions"/>
    </View>
      <View className="label-column">
        <Header value="Attributes"/>
      <RectangleLabels name="attributes" toName="image" value="$attributes"/>
      </View>
      <View className="label-column">
        <Header value="Relationships"/>
      <RectangleLabels name="relationships" toName="image" value="$relationships"/>
      </View>
   
    </View>
    <Image name="image" value="$image"/>
    <Style>
    .label-column .lsf-labels {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
    }
    </Style>
  </View>
  <!-- { "data": {
    "image": "https://htx-pub.s3.amazonaws.com/templates/visual-genome/panda.jpeg",
    "regions": [{
      "value": "panda bear holding something in it's paw"
    }, {
      "value": "trees behind the panda out of focus"
    }, {
        "value": "piece of bamboo in panda's paw"
      }, {
        "value": "bamboo next to panda"
      }, {
        "value": "the panda is cute"
      }],
    "attributes": [{
      "value": "markings is black"
    }, {
      "value": "nose is black"
    }, {
      "value": "face is round"
    }, {
        "value": "wood is round"
      }],
    "relationships": [{
      "value": "hole ON log"
    }, {
      "value": "tree BEHIND bear"
    }, {
        "value": "mouth OF panda"
      }]
  }}-->
