title: "基于内容的图像搜索"
type: community
group: 排序与评分
image: /static/templates/content-based-image-search.png
details: |
  <h1>评估图像搜索的相关性</h1>
  <dl>
    <dt>行业应用</dt>
    <dd>电商、视觉搜索、图像检索、数字资产管理、版权检测</dd>
    <dt>相关模型</dt>
    <dd>CLIP、ResNet、ViT</dd>
    <dt>领域术语</dt>
    <dd>图像搜索、视觉搜索、CBIR、图像检索</dd>
  </dl>
config: |
  <View>
    <Image name="query" value="$query_image" />
    <Header value="Choose similar images:" />
    <View style="display: grid; column-gap: 8px; grid-template: auto/1fr 1fr 1fr">
      <Image name="image1" value="$image1" />
      <Image name="image2" value="$image2" />
      <Image name="image3" value="$image3" />
    </View>
    <Choices name="similar" toName="query" required="true" choice="multiple">
      <Choice value="One" />
      <Choice value="Two" />
      <Choice value="Three" />
    </Choices>
    <Style>
      [dataneedsupdate]~div form {display: flex}
      [dataneedsupdate]~div form>* {flex-grow:1;margin-left:8px}
    </Style>
  </View>

