title: "命名實體識別"
type: community
group: 自然語言處理
order: 3
image: /static/templates/named-entity-recognition.png
details: |
  <h1>從文字中提取命名實體</h1>
  <dl>
    <dt>產業應用</dt>
    <dd>法律文件、合約、醫療記錄、臨床筆記、新聞文章、新聞報導、金融文件、合規、監管、盡職調查、文件處理、文字挖掘、知識提取、結構化資料提取</dd>
    <dt>相關模型</dt>
    <dd>BERT、spaCy、Stanford NER、Flair、transformer 模型</dd>
    <dt>領域術語</dt>
    <dd>NLP、NER、資訊抽取、實體提取、實體連結</dd>
  </dl>
config: |
  <View>
    <Labels name="label" toName="text">
      <Label value="PER" background="red"/>
      <Label value="ORG" background="darkorange"/>
      <Label value="LOC" background="orange"/>
      <Label value="MISC" background="green"/>
    </Labels>

    <Text name="text" value="$text"/>
  </View>

