title: "图像分类"
type: community
group: 计算机视觉
image: /static/templates/image-classification.png
details: |
  <h1>对图像进行分类</h1>
  <dl>
    <dt>行业应用</dt>
    <dd>内容审核、安全检测、不当内容、NSFW检测、社交媒体审核、平台安全、社区准则</dd>
    <dt>相关模型</dt>
    <dd>ResNet、EfficientNet、Vision Transformer、CNN、ConvNet</dd>
    <dt>领域术语</dt>
    <dd>图像标记、视觉分类、多类别、单标签</dd>
  </dl>
config: |
  <View>
    <Image name="image" value="$image"/>
    <Choices name="choice" toName="image">
      <Choice value="Adult content"/>
      <Choice value="Weapons" />
      <Choice value="Violence" />
    </Choices>
  </View>

