# Generated by Django 5.1.5 on 2025-02-11 21:16

import annoying.fields
import django.db.models.deletion
from django.db import migrations, models

#迁移
#创建一张叫 JWTSettings 的表，用来存储每个组织的 JWT 登录配置
#在数据库里建一张表，存「每个组织要不要开 JWT 登录、令牌有效期多久」
#JWT 就是你接口用的 Token 登录
#这张表控制是否开启令牌验证



#Django 迁移类，负责改数据库
class Migration(migrations.Migration):
    #这是第一次创建这张表
    initial = True
    #必须先执行组织（organizations）的迁移，因为这张表依赖组织表
    dependencies = [
        ('organizations', '0006_alter_organizationmember_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTSettings',
            fields=[
                ('organization', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='jwt', serialize=False, to='organizations.organization')),
                ('api_tokens_enabled', models.BooleanField(default=False, help_text='Enable JWT API token authentication for this organization', verbose_name='JWT API tokens enabled')),
                ('api_token_ttl_days', models.IntegerField(default=73000, help_text='Number of days before JWT API tokens expire', verbose_name='JWT API token time to live (days)')),
                ('legacy_api_tokens_enabled', models.BooleanField(default=True, help_text='Enable legacy API token authentication for this organization', verbose_name='legacy API tokens enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
    ]
