title: "关系抽取"
type: community
group: 自然语言处理
order: 5
image: /static/templates/relation-extraction.png
details: |
  <h1>标注文本中实体之间的关系</h1>
  <dl>
    <dt>行业应用</dt>
    <dd>知识图谱、药物发现、法律分析、情报分析、生物医学研究、供应链分析</dd>
    <dt>相关模型</dt>
    <dd>BERT、BioBERT、spaCy、REBEL</dd>
    <dt>领域术语</dt>
    <dd>关系提取、实体关系、知识图谱、三元组</dd>
  </dl>
config: |
  <View>
     <Relations>
      <Relation value="org:founded_by"/>
      <Relation value="org:founded"/>
    </Relations>
    <Labels name="label" toName="text">
      <Label value="Organization" background="orange"/>
      <Label value="Person" background="green"/>
      <Label value="Datetime" background="blue"/>
    </Labels>

    <Text name="text" value="$text"/>
  </View>

  <!-- {"data": {
    "text": "Microsoft was founded by Bill Gates and Paul Allen on April 4, 1975, to develop and sell BASIC interpreters for the Altair 8800."
  }} -->

