export const DEFAULT_HOTKEYS = [
  {
    id: 100,
    section: "annotation",
    element: "annotation:submit",
    label: "common.hotkeys.keys.annotation.submit",
    key: "ctrl+enter",
    description: "common.hotkeys.keys.annotation.submit.description",
    active: true,
  },
  {
    id: 200,
    section: "annotation",
    element: "annotation:skip",
    label: "common.hotkeys.keys.annotation.skip",
    key: "ctrl+space",
    description: "common.hotkeys.keys.annotation.skip.description",
    active: true,
  },
  {
    id: 300,
    section: "annotation",
    element: "annotation:undo",
    label: "common.hotkeys.keys.annotation.undo",
    key: "ctrl+z",
    description: "common.hotkeys.keys.annotation.undo.description",
    active: true,
  },
  {
    id: 400,
    section: "annotation",
    element: "annotation:redo",
    label: "common.hotkeys.keys.annotation.redo",
    key: "ctrl+shift+z",
    description: "common.hotkeys.keys.annotation.redo.description",
    active: true,
  },
  // Data Manager
  {
    id: 500,
    section: "data_manager",
    element: "dm.focus-previous",
    label: "common.hotkeys.keys.data_manager.focus_previous",
    key: "shift+up",
    description: "common.hotkeys.keys.data_manager.focus_previous.description",
    active: true,
  },
  {
    id: 600,
    section: "data_manager",
    element: "dm.focus-next",
    label: "common.hotkeys.keys.data_manager.focus_next",
    key: "shift+down",
    description: "common.hotkeys.keys.data_manager.focus_next.description",
    active: true,
  },
  {
    id: 700,
    section: "data_manager",
    element: "dm.close-labeling",
    label: "common.hotkeys.keys.data_manager.close_labeling",
    key: "shift+left",
    description: "common.hotkeys.keys.data_manager.close_labeling.description",
    active: true,
  },
  {
    id: 800,
    section: "data_manager",
    element: "dm.open-labeling",
    label: "common.hotkeys.keys.data_manager.open_labeling",
    key: "shift+right",
    description: "common.hotkeys.keys.data_manager.open_labeling.description",
    active: true,
  },
  {
    id: 900,
    section: "data_manager",
    element: "dm.toggle-bulk-sidebar-minimization",
    label: "common.hotkeys.keys.data_manager.toggle_bulk_sidebar_minimization",
    key: "shift+.",
    description:
      "common.hotkeys.keys.data_manager.toggle_bulk_sidebar_minimization.description",
    active: true,
  },
  // Region Management
  {
    id: 1100,
    section: "regions",
    element: "region:delete-all",
    label: "common.hotkeys.keys.regions.delete_all",
    key: "ctrl+backspace",
    description: "common.hotkeys.keys.regions.delete_all.description",
    active: true,
  },
  {
    id: 1200,
    section: "regions",
    element: "region:focus",
    label: "common.hotkeys.keys.regions.focus",
    key: "enter",
    description: "common.hotkeys.keys.regions.focus.description",
    active: true,
  },
  {
    id: 1300,
    section: "regions",
    element: "region:relation",
    label: "common.hotkeys.keys.regions.relation",
    key: "alt+r",
    description: "common.hotkeys.keys.regions.relation.description",
    active: true,
  },
  {
    id: 1400,
    section: "regions",
    element: "region:visibility",
    label: "common.hotkeys.keys.regions.visibility",
    key: "alt+h",
    description: "common.hotkeys.keys.regions.visibility.description",
    active: true,
  },
  {
    id: 1500,
    section: "regions",
    element: "region:visibility-all",
    label: "common.hotkeys.keys.regions.visibility_all",
    key: "ctrl+h",
    description: "common.hotkeys.keys.regions.visibility_all.description",
    active: true,
  },
  {
    id: 1600,
    section: "regions",
    element: "region:lock",
    label: "common.hotkeys.keys.regions.lock",
    key: "alt+l",
    description: "common.hotkeys.keys.regions.lock.description",
    active: true,
  },
  {
    id: 1700,
    section: "regions",
    element: "region:meta",
    label: "common.hotkeys.keys.regions.meta",
    key: "alt+m",
    description: "common.hotkeys.keys.regions.meta.description",
    active: true,
  },
  {
    id: 1800,
    section: "regions",
    element: "region:unselect",
    label: "common.hotkeys.keys.regions.unselect",
    key: "u",
    description: "common.hotkeys.keys.regions.unselect.description",
    active: true,
  },
  {
    id: 1900,
    section: "regions",
    element: "region:exit",
    label: "common.hotkeys.keys.regions.exit",
    key: "escape",
    description: "common.hotkeys.keys.regions.exit.description",
    active: true,
  },
  {
    id: 2000,
    section: "regions",
    element: "region:delete",
    label: "common.hotkeys.keys.regions.delete",
    key: "backspace",
    description: "common.hotkeys.keys.regions.delete.description",
    active: true,
  },
  {
    id: 2100,
    section: "regions",
    element: "region:cycle",
    label: "common.hotkeys.keys.regions.cycle",
    key: "alt+.",
    description: "common.hotkeys.keys.regions.cycle.description",
    active: true,
  },
  {
    id: 2200,
    section: "regions",
    element: "region:duplicate",
    label: "common.hotkeys.keys.regions.duplicate",
    key: "ctrl+d",
    description: "common.hotkeys.keys.regions.duplicate.description",
    active: true,
  },
  {
    id: 2300,
    section: "regions",
    element: "segment:delete",
    label: "common.hotkeys.keys.regions.segment_delete",
    key: "delete",
    description: "common.hotkeys.keys.regions.segment_delete.description",
    active: true,
  },
  // Editor - Audio Controls
  {
    id: 2400,
    section: "audio",
    element: "audio:back",
    label: "common.hotkeys.keys.audio.back",
    key: "ctrl+b",
    description: "common.hotkeys.keys.audio.back.description",
    active: true,
  },
  {
    id: 2500,
    section: "audio",
    element: "audio:playpause",
    label: "common.hotkeys.keys.audio.playpause",
    key: "ctrl+p",
    description: "common.hotkeys.keys.audio.playpause.description",
    active: true,
  },
  {
    id: 2600,
    section: "audio",
    element: "audio:step-backward",
    label: "common.hotkeys.keys.audio.step_backward",
    key: "alt+a",
    description: "common.hotkeys.keys.audio.step_backward.description",
    active: true,
  },
  {
    id: 2700,
    section: "audio",
    element: "audio:step-forward",
    label: "common.hotkeys.keys.audio.step_forward",
    key: "alt+d",
    description: "common.hotkeys.keys.audio.step_forward.description",
    active: true,
  },
  // Editor - Video Controls
  {
    id: 2800,
    section: "video",
    element: "media:playpause",
    label: "common.hotkeys.keys.video.playpause",
    key: "ctrl+alt+space",
    description: "common.hotkeys.keys.video.playpause.description",
    active: true,
  },
  {
    id: 2900,
    section: "video",
    element: "media:step-backward",
    label: "common.hotkeys.keys.video.step_backward",
    key: "alt+left",
    description: "common.hotkeys.keys.video.step_backward.description",
    active: true,
  },
  {
    id: 3000,
    section: "video",
    element: "media:step-forward",
    label: "common.hotkeys.keys.video.step_forward",
    key: "alt+right",
    description: "common.hotkeys.keys.video.step_forward.description",
    active: true,
  },
  {
    id: 3100,
    section: "video",
    element: "video:keyframe-backward",
    label: "common.hotkeys.keys.video.keyframe_backward",
    key: "ctrl+alt+left",
    description: "common.hotkeys.keys.video.keyframe_backward.description",
    active: true,
  },
  {
    id: 3200,
    section: "video",
    element: "video:keyframe-forward",
    label: "common.hotkeys.keys.video.keyframe_forward",
    key: "ctrl+alt+right",
    description: "common.hotkeys.keys.video.keyframe_forward.description",
    active: true,
  },
  {
    id: 3300,
    section: "video",
    element: "video:backward",
    label: "common.hotkeys.keys.video.backward",
    key: "alt+left",
    description: "common.hotkeys.keys.video.backward.description",
    active: true,
  },
  {
    id: 3400,
    section: "video",
    element: "video:rewind",
    label: "common.hotkeys.keys.video.rewind",
    key: "shift+ctrl+alt+left",
    description: "common.hotkeys.keys.video.rewind.description",
    active: true,
  },
  {
    id: 3500,
    section: "video",
    element: "video:forward",
    label: "common.hotkeys.keys.video.forward",
    key: "shift+alt+right",
    description: "common.hotkeys.keys.video.forward.description",
    active: true,
  },
  {
    id: 3600,
    section: "video",
    element: "video:fastforward",
    label: "common.hotkeys.keys.video.fastforward",
    key: "shift+ctrl+alt+right",
    description: "common.hotkeys.keys.video.fastforward.description",
    active: true,
  },
  {
    id: 3700,
    section: "video",
    element: "video:hop-backward",
    label: "common.hotkeys.keys.video.hop_backward",
    key: "shift+alt+left",
    description: "common.hotkeys.keys.video.hop_backward.description",
    active: true,
  },
  {
    id: 3800,
    section: "video",
    element: "video:hop-forward",
    label: "common.hotkeys.keys.video.hop_forward",
    key: "shift+alt+right",
    description: "common.hotkeys.keys.video.hop_forward.description",
    active: true,
  },
  // Editor - Time Series Controls
  {
    id: 3900,
    section: "timeseries",
    element: "ts:grow-left",
    label: "common.hotkeys.keys.timeseries.grow_left",
    key: "left",
    description: "common.hotkeys.keys.timeseries.grow_left.description",
    active: true,
  },
  {
    id: 4000,
    section: "timeseries",
    element: "ts:grow-right",
    label: "common.hotkeys.keys.timeseries.grow_right",
    key: "right",
    description: "common.hotkeys.keys.timeseries.grow_right.description",
    active: true,
  },
  {
    id: 4100,
    section: "timeseries",
    element: "ts:shrink-left",
    label: "common.hotkeys.keys.timeseries.shrink_left",
    key: "alt+left",
    description: "common.hotkeys.keys.timeseries.shrink_left.description",
    active: true,
  },
  {
    id: 4200,
    section: "timeseries",
    element: "ts:shrink-right",
    label: "common.hotkeys.keys.timeseries.shrink_right",
    key: "alt+right",
    description: "common.hotkeys.keys.timeseries.shrink_right.description",
    active: true,
  },
  {
    id: 4300,
    section: "timeseries",
    element: "ts:grow-left-large",
    label: "common.hotkeys.keys.timeseries.grow_left_large",
    key: "shift+left",
    description: "common.hotkeys.keys.timeseries.grow_left_large.description",
    active: true,
  },
  {
    id: 4400,
    section: "timeseries",
    element: "ts:grow-right-large",
    label: "common.hotkeys.keys.timeseries.grow_right_large",
    key: "shift+right",
    description: "common.hotkeys.keys.timeseries.grow_right_large.description",
    active: true,
  },
  {
    id: 4500,
    section: "timeseries",
    element: "ts:shrink-left-large",
    label: "common.hotkeys.keys.timeseries.shrink_left_large",
    key: "shift+alt+left",
    description: "common.hotkeys.keys.timeseries.shrink_left_large.description",
    active: true,
  },
  {
    id: 4600,
    section: "timeseries",
    element: "ts:shrink-right-large",
    label: "common.hotkeys.keys.timeseries.shrink_right_large",
    key: "shift+alt+right",
    description:
      "common.hotkeys.keys.timeseries.shrink_right_large.description",
    active: true,
  },
  // Image Gallery Controls
  {
    id: 4700,
    section: "image_gallery",
    element: "image:prev",
    label: "common.hotkeys.keys.image_gallery.prev",
    key: "ctrl+left",
    description: "common.hotkeys.keys.image_gallery.prev.description",
    active: true,
  },
  {
    id: 4800,
    section: "image_gallery",
    element: "image:next",
    label: "common.hotkeys.keys.image_gallery.next",
    key: "ctrl+right",
    description: "common.hotkeys.keys.image_gallery.next.description",
    active: true,
  },
  {
    id: 5000,
    section: "tools",
    element: "tool:zoom-in",
    label: "common.hotkeys.keys.tools.zoom_in",
    key: "ctrl+plus",
    description: "common.hotkeys.keys.tools.zoom_in.description",
    active: true,
  },
  {
    id: 5100,
    section: "tools",
    element: "tool:pan-image",
    label: "common.hotkeys.keys.tools.pan_image",
    key: "H",
    description: "common.hotkeys.keys.tools.pan_image.description",
    active: true,
  },
  {
    id: 5200,
    section: "tools",
    element: "tool:zoom-to-fit",
    label: "common.hotkeys.keys.tools.zoom_to_fit",
    key: "shift+1",
    description: "common.hotkeys.keys.tools.zoom_to_fit.description",
    active: true,
  },
  {
    id: 5300,
    section: "tools",
    element: "tool:zoom-to-actual",
    label: "common.hotkeys.keys.tools.zoom_to_actual",
    key: "shift+2",
    description: "common.hotkeys.keys.tools.zoom_to_actual.description",
    active: true,
  },
  {
    id: 5400,
    section: "tools",
    element: "tool:zoom-out",
    label: "common.hotkeys.keys.tools.zoom_out",
    key: "ctrl+minus",
    description: "common.hotkeys.keys.tools.zoom_out.description",
    active: true,
  },
  {
    id: 5401,
    section: "tools",
    element: "tool:move",
    label: "common.hotkeys.keys.tools.move",
    key: "V",
    description: "common.hotkeys.keys.tools.move.description",
    active: true,
  },
  {
    id: 5402,
    section: "tools",
    element: "tool:brush",
    label: "common.hotkeys.keys.tools.brush",
    key: "B",
    description: "common.hotkeys.keys.tools.brush.description",
    active: true,
  },
  {
    id: 5500,
    section: "tools",
    element: "tool:ellipse",
    label: "common.hotkeys.keys.tools.ellipse",
    key: "O",
    description: "common.hotkeys.keys.tools.ellipse.description",
    active: true,
  },
  {
    id: 5600,
    section: "tools",
    element: "tool:eraser",
    label: "common.hotkeys.keys.tools.eraser",
    key: "E",
    description: "common.hotkeys.keys.tools.eraser.description",
    active: true,
  },
  {
    id: 5700,
    section: "tools",
    element: "tool:auto-detect",
    label: "common.hotkeys.keys.tools.auto_detect",
    key: "M",
    description: "common.hotkeys.keys.tools.auto_detect.description",
    active: true,
  },
  {
    id: 5900,
    section: "tools",
    element: "tool:key-point",
    label: "common.hotkeys.keys.tools.key_point",
    key: "K",
    description: "common.hotkeys.keys.tools.key_point.description",
    active: true,
  },
  {
    id: 6000,
    section: "tools",
    element: "tool:magic-wand",
    label: "common.hotkeys.keys.tools.magic_wand",
    key: "W",
    description: "common.hotkeys.keys.tools.magic_wand.description",
    active: true,
  },
  {
    id: 6100,
    section: "tools",
    element: "tool:polygon",
    label: "common.hotkeys.keys.tools.polygon",
    key: "P",
    description: "common.hotkeys.keys.tools.polygon.description",
    active: true,
  },
  {
    id: 6200,
    section: "tools",
    element: "tool:rect",
    label: "common.hotkeys.keys.tools.rect",
    key: "R",
    description: "common.hotkeys.keys.tools.rect.description",
    active: true,
  },
  {
    id: 6201,
    section: "tools",
    element: "tool:rect-3point",
    label: "common.hotkeys.keys.tools.rect_3point",
    key: "shift+R",
    description: "common.hotkeys.keys.tools.rect_3point.description",
    active: true,
  },
  {
    id: 6300,
    section: "tools",
    element: "tool:rotate-left",
    label: "common.hotkeys.keys.tools.rotate_left",
    key: "alt+left",
    description: "common.hotkeys.keys.tools.rotate_left.description",
    active: true,
  },
  {
    id: 6400,
    section: "tools",
    element: "tool:rotate-right",
    label: "common.hotkeys.keys.tools.rotate_right",
    key: "alt+right",
    description: "common.hotkeys.keys.tools.rotate_right.description",
    active: true,
  },
  {
    id: 6700,
    section: "tools",
    element: "tool:decrease-tool",
    label: "common.hotkeys.keys.tools.decrease_tool",
    key: "[",
    description: "common.hotkeys.keys.tools.decrease_tool.description",
    active: true,
  },
  {
    id: 6800,
    section: "tools",
    element: "tool:increase-tool",
    label: "common.hotkeys.keys.tools.increase_tool",
    key: "]",
    description: "common.hotkeys.keys.tools.increase_tool.description",
    active: true,
  },
  // Paragraph Navigation
  {
    id: 6900,
    section: "paragraphs",
    element: "phrases:next-phrase",
    label: "common.hotkeys.keys.paragraphs.next_phrase",
    key: "ctrl+down",
    description: "common.hotkeys.keys.paragraphs.next_phrase.description",
    active: true,
  },
  {
    id: 7000,
    section: "paragraphs",
    element: "phrases:previous-phrase",
    label: "common.hotkeys.keys.paragraphs.previous_phrase",
    key: "ctrl+up",
    description: "common.hotkeys.keys.paragraphs.previous_phrase.description",
    active: true,
  },
  {
    id: 7100,
    section: "paragraphs",
    element: "phrases:select_all_annotate",
    label: "common.hotkeys.keys.paragraphs.select_all_annotate",
    key: "ctrl+shift+a",
    description:
      "common.hotkeys.keys.paragraphs.select_all_annotate.description",
    active: true,
  },
  {
    id: 7200,
    section: "paragraphs",
    element: "phrases:next-region",
    label: "common.hotkeys.keys.paragraphs.next_region",
    key: "ctrl+right",
    description: "common.hotkeys.keys.paragraphs.next_region.description",
    active: true,
  },
  {
    id: 7300,
    section: "paragraphs",
    element: "phrases:previous-region",
    label: "common.hotkeys.keys.paragraphs.previous_region",
    key: "ctrl+left",
    description: "common.hotkeys.keys.paragraphs.previous_region.description",
    active: true,
  },
];

export const HOTKEY_SECTIONS = [
  {
    id: "annotation",
    title: "common.hotkeys.sections.annotation.title",
    description: "common.hotkeys.sections.annotation.description",
  },
  {
    id: "data_manager",
    title: "common.hotkeys.sections.data_manager.title",
    description: "common.hotkeys.sections.data_manager.description",
  },
  {
    id: "regions",
    title: "common.hotkeys.sections.regions.title",
    description: "common.hotkeys.sections.regions.description",
  },
  {
    id: "tools",
    title: "common.hotkeys.sections.tools.title",
    description: "common.hotkeys.sections.tools.description",
  },
  {
    id: "audio",
    title: "common.hotkeys.sections.audio.title",
    description: "common.hotkeys.sections.audio.description",
  },
  {
    id: "video",
    title: "common.hotkeys.sections.video.title",
    description: "common.hotkeys.sections.video.description",
  },
  {
    id: "timeseries",
    title: "common.hotkeys.sections.timeseries.title",
    description: "common.hotkeys.sections.timeseries.description",
  },
  {
    id: "image_gallery",
    title: "common.hotkeys.sections.image_gallery.title",
    description: "common.hotkeys.sections.image_gallery.description",
  },
  {
    id: "paragraphs",
    title: "common.hotkeys.sections.paragraphs.title",
    description: "common.hotkeys.sections.paragraphs.description",
  },
];

/**
 * URL patterns mapped to their corresponding hotkey sections
 * Used to automatically determine which shortcuts to display based on current page
 */
export const URL_TO_SECTION_MAPPING = [
  {
    regex: /\/projects\/\d+\/data\/?\?.*task=\d+/i,
    section: ["annotation", "regions"],
  },
  {
    regex: /\/projects\/\d+\/data\/?$/i,
    section: "data_manager",
  },
];
